server:
  port: 8888

spring:
  application:
    name: encryption
  redis:
    host: 127.0.0.1      # Redis服务器地址
    port: 6379           # 默认端口
    password:            # 密码（没有则省略）
    database: 0          # 数据库索引（0-15）
    lettuce:
      pool:
        max-active: 8    # 连接池最大连接数
        max-idle: 8      # 连接池最大空闲连接
        min-idle: 0      # 连接池最小空闲连接
        max-wait: 100ms  # 获取连接的最大等待时间

# 时间戳及随机字符串超时时间(分钟)
security:
  timestamp:
    tolerance: 5

# RSA密钥对
rsa:
  private-key-path: classpath:rsa_keys/private_key.pem
  public-key-path: classpath:rsa_keys/public_key.pem